defaults:
  - override /model@_global_: deep_coRNN

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    storage: null
    study_name: deep_coRNN_hyperparameter_study
    n_trials: 20
    n_jobs: 1
    search_space:
      n_hid:
        type: categorial
        choices: [32, 64, 128] 
      nlayers:
        type: int
        bounds:
          - 3
          - 30
      epsilon:
        type: categorial
        coices: [0.0, 0.1, 0.5, 1.0]
      dt: 
        type: categorial
        coices: [0.5, 1.0, 2.0]
      dropout: 
        type: categorial
        coices: [0.05, 0.1, 0.2]

  


  