



train_folder: "${data_path_local}/ccai_demo/data/FCN_ERA5_data_v0/out_of_sample/"
years: [2018]
val_file: "${data_path_local}/ccai_demo/data/FCN_ERA5_data_v0/out_of_sample/2018.h5"
strategy: "auto"
nodes: 1
devices: 1

global_means: "${data_path_local}/ccai_demo/additional/stats_v0/global_means.npy"
global_stds: "${data_path_local}/ccai_demo/additional/stats_v0/global_stds.npy"
time_means: "${data_path_local}/ccai_demo/additional/stats_v0/time_means.npy"
land_sea_mask: "${data_path_local}/ccai_demo/additional/stats_v0/land_sea_mask.npy"
num_workers: 1

